function capabilities = fastbvar_capabilities()
%FASTBVAR_CAPABILITIES Machine-readable validation/dispatch status.

capabilities.upstream_commit = ...
    '3975e6597cb23d82e4ebad162af29b2a1105b395';
capabilities.schema_version = 1;
capabilities.numeric_abs_tol = 1e-6;
capabilities.numeric_rel_tol = 1e-6;
capabilities.features = struct( ...
    'name', {'default_estimation', 'irregular_missing', ...
             'mixed_frequency_flow', 'rng_stream_preservation', ...
             'all_other_upstream_options'}, ...
    'status', {'validated_legacy', 'validated_fast', ...
               'validated_fast', 'validated_fast', ...
               'not_yet_validated'}, ...
    'optimized', {true, true, true, true, false}, ...
    'test', {'small_complete', 'small_irregular', ...
             'small_mixed_frequency', 'rng_optout', ''});
end
