function registry = fastbvar_validation_registry()
%FASTBVAR_VALIDATION_REGISTRY Built-in exactness coverage by option signature.

registry.baseline_fields = {'K','hor','fhor','noprint','verify_mode'};
registry.known_fields = { ...
    'ElasticNet','K','K_shrinkage','Lasso','Omegaf','Ridge', ...
    'bvar_prior_decay','bvar_prior_lambda','bvar_prior_mu', ...
    'bvar_prior_omega','bvar_prior_tau','connectedness','controls', ...
    'endo_index','endo_path','exo_index','exogenous','exogenous_block', ...
    'fhor','firstobs','heterosked_regimes','heterosked_weights', ...
    'hmoments','hmoments_eig','hor','irf_1STD','long_run_irf', ...
    'index_est','lb','max_compute','max_minn_hyper','mf_varindex', ...
    'minn_prior_decay', ...
    'minn_prior_lambda','minn_prior_mu','minn_prior_omega', ...
    'minn_prior_tau','mixed_freq_index','narrative','nethor', ...
    'noconstant','non_explosive_','noprint','pandemic','presample', ...
    'prior','priors','proxy','proxy_end','robust_bayes', ...
    'robust_credible_regions','set_irf','signs','timetrend','var_pos', ...
    'ub','verify_mode','vnames','zeros_signs','objective_function'};

% An arbitrary optimizer callback is accepted for upstream compatibility,
% but no finite fixture set can certify user-supplied code.
registry.always_unvalidated = {'objective_function'};

% Populated only by combinations exercised in verify_option_coverage.m.
registry.validated_signatures = { ...
    '<baseline>', ...
    'vnames', ...
    'firstobs', ...
    'presample', ...
    'noconstant', ...
    'timetrend', ...
    'non_explosive_=1', ...
    'heterosked_weights', ...
    'robust_bayes=1', ...
    'robust_bayes=2', ...
    'K_shrinkage+robust_bayes=1', ...
    'exogenous', ...
    'controls', ...
    'exogenous_block', ...
    'prior:minnesota', ...
    'priors:minnesota', ...
    'priors:conjugate', ...
    'priors:plr', ...
    'minn_prior_tau', ...
    'minn_prior_decay', ...
    'minn_prior_lambda', ...
    'minn_prior_mu', ...
    'minn_prior_omega', ...
    'bvar_prior_mu+bvar_prior_tau', ...
    'bvar_prior_decay+bvar_prior_mu', ...
    'bvar_prior_lambda+bvar_prior_mu', ...
    'bvar_prior_mu', ...
    'bvar_prior_omega', ...
    'max_minn_hyper=1', ...
    'index_est+max_compute=7+max_minn_hyper=1', ...
    'max_compute=7+max_minn_hyper=1', ...
    'index_est+lb+max_compute=2+max_minn_hyper=1', ...
    'index_est+max_compute=2+max_minn_hyper=1+ub', ...
    'pandemic', ...
    'irf_1STD=0', ...
    'long_run_irf=1', ...
    'heterosked_regimes', ...
    'signs', ...
    'narrative', ...
    'zeros_signs', ...
    'var_pos+zeros_signs', ...
    'proxy', ...
    'proxy+proxy_end', ...
    'hmoments', ...
    'hmoments_eig=4', ...
    'set_irf=1+signs', ...
    'robust_credible_regions:KG=0', ...
    'robust_credible_regions:KG=1+signs', ...
    'endo_path', ...
    'endo_index+endo_path', ...
    'endo_index+endo_path+exo_index', ...
    'Omegaf', ...
    'mf_varindex', ...
    'mixed_freq_index', ...
    'nethor', ...
    'ElasticNet+Lasso+Ridge+connectedness=1', ...
    'Ridge', ...
    'Lasso', ...
    'ElasticNet'};
end
